apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModelSource
metadata:
  name: amd-aimsource-stable
spec:
  maxModels: 500
  filters:
    - image: amdenterpriseai/aim-*
      exclude:
        - amdenterpriseai/aim-base
  versions:
    - ">=0.8.4"
---
apiVersion: aim.silogen.ai/v1alpha1
kind: AIMClusterModel
metadata:
  name: mahesh509-sarvamai-v1-0
spec:
  image: mahesh509/sarvamai:v1.0